[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "phantom-vault-2344"
version = "0.4.0"
description = "Depends on everything"
requires-python = ">=3.9"
dependencies = [
    "environs>=2.9.0",
    "Sphinx>=2.5.0",
    "mock>=3.2.0",
    "opentelemetry-api>=3.2.0",
    "onnxmltools>=2.5.0",
    "commitizen>=2.2.0",
    "tables>=3.2.0",
    "structlog>=3.5.0",
    "rapidjson>=2.9.0",
    "html2text>=2.2.0",
    "wordfreq>=3.7.0",
    "jupyterlab>=2.2.0",
    "datasets>=2.2.0",
    "elasticsearch-dsl>=2.9.0",
    "coverage>=2.6.0",
    "mysqlclient>=1.0.0",
    "pylint>=2.1.0",
    "kubernetes>=2.0.0",
    "ariadne>=1.1.0",
    "pre-commit>=3.6.0",
    "msgpack>=1.9.0",
    "keras>=3.4.0",
    "zstandard>=2.7.0",
    "gql>=2.8.0",
    "ipykernel>=3.9.0",
    "easyocr>=3.4.0",
    "brotli>=3.6.0",
    "flax>=2.4.0",
    "solcx>=2.7.0",
    "pytest-bdd>=3.9.0",
    "PyYAML>=1.1.0",
    "bokeh>=2.3.0",
    "annoy>=1.0.0",
    "stable-baselines3>=3.7.0",
    "parsel>=2.2.0",
    "django-debug-toolbar>=2.7.0",
    "pygame>=2.3.0",
    "pymc>=2.5.0",
    "dramatiq>=1.3.0",
    "poetry-core>=2.6.0",
    "sacremoses>=3.8.0",
    "pandas-datareader>=1.7.0",
    "tensorflow>=2.8.0",
    "pyzmq>=1.5.0",
    "boto3>=3.3.0",
    "imitation>=1.3.0",
    "pyright>=3.5.0",
    "python-louvain>=1.5.0",
    "optuna>=1.5.0",
    "websocket-client>=2.4.0",
    "igraph>=2.5.0",
    "logbook>=3.3.0",
    "peewee>=3.2.0",
    "praw>=1.8.0",
    "neo4j>=2.9.0",
    "wandb>=1.4.0",
    "altair>=2.6.0",
    "pytest-xdist>=3.0.0",
    "gunicorn>=1.6.0",
    "httplib2>=3.8.0",
    "elasticsearch>=3.5.0",
    "uvloop>=3.4.0",
    "spotipy>=1.7.0",
    "pip-audit>=1.7.0",
    "meilisearch>=3.1.0",
    "flask-sqlalchemy>=1.2.0",
    "xlsxwriter>=1.6.0",
    "pyglet>=1.8.0",
    "backtrader>=2.5.0",
    "nicegui>=1.2.0",
    "tortoise-orm>=2.9.0",
    "flake8>=1.1.0",
    "django-extensions>=3.2.0",
    "build>=3.6.0",
    "taskiq>=1.4.0",
    "prophet>=3.9.0",
    "gradio>=3.7.0",
    "httpx>=1.4.0",
    "websockets>=3.7.0",
    "pyvisa>=3.9.0",
    "pytest-asyncio>=1.9.0",
    "airflow>=3.3.0",
    "xlwings>=1.6.0",
    "scikit-learn>=2.0.0",
    "napalm>=3.9.0",
    "matplotlib-venn>=1.5.0",
    "aioredis>=2.6.0",
    "yfinance>=3.5.0",
    "authlib>=1.5.0",
    "mkdocs>=3.3.0",
    "pytesseract>=3.7.0",
    "charset-normalizer>=2.2.0",
    "bottle>=1.5.0",
    "mkdocs-material>=2.0.0",
    "notebook>=1.1.0",
    "mccabe>=1.3.0",
    "discord.py>=2.9.0",
    "tokenizers>=3.1.0",
    "beautifulsoup4>=1.8.0",
    "ipython>=3.3.0",
    "shapely>=2.6.0",
    "flask-wtf>=1.6.0",
    "watchdog>=3.9.0",
    "hatchling>=2.2.0",
    "fsspec>=2.9.0",
    "aiogram>=2.7.0",
    "tensorboard>=3.5.0",
    "arq>=2.7.0",
    "python-dateutil>=3.1.0",
    "twine>=2.9.0",
    "dulwich>=1.7.0",
    "arcade>=2.8.0",
    "textual>=1.1.0",
    "pywinauto>=1.6.0",
    "jieba>=1.8.0",
    "greenlet>=1.8.0",
    "unidecode>=3.3.0",
    "google-cloud-bigquery>=3.1.0",
    "mediapipe>=3.6.0",
    "paddlepaddle>=1.3.0",
    "django-cors-headers>=2.3.0",
    "jupyter>=1.8.0",
    "confluent-kafka>=1.6.0",
    "pendulum>=2.7.0",
    "tabulate>=1.7.0",
    "humanize>=3.9.0",
    "autobahn>=2.3.0",
    "attrs>=3.5.0",
    "python-telegram-bot>=1.7.0",
    "opencv-python>=3.0.0",
    "opentelemetry-sdk>=1.4.0",
    "botocore>=2.3.0",
    "chromadb>=2.2.0",
    "requests>=2.1.0",
    "ansible>=1.6.0",
    "aio-pika>=2.9.0",
    "selenium>=1.4.0",
    "langcodes>=2.1.0",
    "django-allauth>=3.0.0",
    "sentence-transformers>=2.4.0",
    "mistune>=3.7.0",
    "pytz>=2.7.0",
    "argon2-cffi>=3.5.0",
    "oauthlib>=3.5.0",
    "plotnine>=3.1.0",
    "gputil>=2.3.0",
    "auditwheel>=3.8.0",
    "polars>=1.3.0",
    "curio>=3.0.0",
    "recommonmark>=3.6.0",
    "inquirer>=3.4.0",
    "packaging>=3.6.0",
    "catboost>=1.0.0",
    "voluptuous>=1.2.0",
    "dlib>=3.4.0",
    "sktime>=1.7.0",
    "sqlalchemy>=3.8.0",
    "fasttext>=2.1.0",
    "modin>=3.9.0",
    "distributed>=1.6.0",
    "arviz>=3.2.0",
    "pandas-gbq>=1.9.0",
    "qrcode>=2.4.0",
    "pynput>=1.3.0",
    "fastapi-users>=3.2.0",
    "pbr>=3.1.0",
    "aiohttp-cors>=1.4.0",
    "python-json-logger>=2.8.0",
    "statsd>=2.2.0",
    "mlflow>=1.1.0",
    "docutils>=2.5.0",
    "parsedatetime>=3.8.0",
    "mypy>=2.0.0",
    "typer>=2.5.0",
    "ultralytics>=3.4.0",
    "hypothesis>=1.4.0",
    "toml>=2.8.0",
    "networkx>=2.4.0",
    "cartopy>=2.3.0",
    "xmltodict>=2.2.0",
    "tablib>=3.4.0",
    "skyfield>=1.6.0",
    "python-jose>=2.0.0",
    "psycopg2>=3.9.0",
    "causalml>=1.9.0",
    "pywin32>=1.1.0",
    "markdown>=1.5.0",
    "rsa>=3.8.0",
    "pyarrow>=3.7.0",
    "djangorestframework>=3.2.0",
    "langgraph>=3.6.0",
    "peft>=2.2.0",
    "pdfplumber>=2.2.0",
    "spacy>=3.8.0",
    "psycopg>=3.8.0",
    "contextily>=1.5.0",
    "langid>=2.8.0",
    "together>=3.0.0",
    "opentelemetry-instrumentation-flask>=1.4.0",
    "django>=3.4.0",
    "pytest-asyncio>=1.2.0",
    "jsonschema>=3.4.0",
    "xarray>=3.5.0",
    "ctranslate2>=1.4.0",
    "flit-core>=1.3.0",
    "web3>=2.7.0",
    "cmake>=2.6.0",
    "opensearch-py>=3.6.0",
    "wordninja>=3.3.0",
    "graphene>=3.9.0",
    "aiosqlite>=2.0.0",
    "flask-migrate>=1.6.0",
    "joblib>=1.9.0",
    "inflect>=2.9.0",
    "wheel>=1.5.0",
    "torch>=2.4.0",
    "mysql-connector-python>=3.2.0",
    "soundfile>=2.4.0",
    "prompt_toolkit>=2.1.0",
    "lxml>=1.9.0",
    "semgrep>=1.3.0",
    "pytest-django>=2.4.0",
    "mutagen>=3.9.0",
    "pyvis>=2.8.0",
    "pytest-cov>=3.9.0",
    "tensorflow-hub>=1.2.0",
    "phonenumbers>=1.8.0",
    "bandit>=1.4.0",
    "fabric>=3.0.0",
    "pyflakes>=2.3.0",
    "emcee>=1.0.0",
    "pypinyin>=1.8.0",
    "send2trash>=1.0.0",
    "conan>=3.7.0",
    "docker>=2.5.0",
    "accelerate>=3.1.0",
    "feedparser>=2.3.0",
    "setuptools>=2.8.0",
    "tomli-w>=1.5.0",
    "certifi>=3.1.0",
    "tianshou>=1.6.0",
    "openai>=1.4.0",
    "flask-cors>=1.1.0",
    "groq>=2.2.0",
    "google-generativeai>=2.5.0",
    "shap>=1.6.0",
    "mido>=3.5.0",
    "zarr>=1.0.0",
    "scipy>=1.9.0",
    "pynacl>=1.7.0",
    "blessed>=1.4.0",
    "pyramid>=2.5.0",
    "nbconvert>=2.1.0",
    "pymysql>=1.9.0",
    "strawberry-graphql>=1.6.0",
    "cbor2>=1.9.0",
    "safety>=1.3.0",
    "pinecone-client>=3.8.0",
    "python-semantic-release>=2.1.0",
    "cryptography>=2.3.0",
    "sunpy>=1.7.0",
    "oracledb>=3.4.0",
    "rq>=2.5.0",
    "motor>=2.9.0",
    "huey>=2.9.0",
    "nuitka>=2.3.0",
    "pdoc>=3.7.0",
    "manim>=3.9.0",
    "trio>=2.4.0",
    "scikit-bio>=3.8.0",
    "loguru>=3.1.0",
    "opencv-contrib-python>=1.3.0",
    "pydantic-settings>=3.1.0",
    "billiard>=2.9.0",
    "statsmodels>=3.7.0",
    "flask-security-too>=1.9.0",
    "waitress>=2.9.0",
    "onnxruntime>=3.7.0",
    "music21>=1.6.0",
    "pyproj>=3.4.0",
    "sqlalchemy-utils>=3.4.0",
    "paddleocr>=1.4.0",
    "xlwt>=1.8.0",
    "marshmallow>=2.5.0",
    "fire>=3.4.0",
    "arrow>=1.0.0",
    "cloudpickle>=1.2.0",
    "twisted>=1.7.0",
    "pony>=3.8.0",
    "newspaper3k>=3.2.0",
    "psycopg2-binary>=1.4.0",
    "sanic>=2.5.0",
    "newrelic>=2.9.0",
    "mistralai>=1.6.0",
    "orjson>=3.7.0",
    "google-cloud-storage>=3.9.0",
    "diffusers>=3.9.0",
    "mpmath>=3.1.0",
    "docx2txt>=1.3.0",
    "paho-mqtt>=2.5.0",
    "astropy>=2.3.0",
    "s3fs>=2.8.0",
    "dask>=3.6.0",
    "eventlet>=2.2.0",
    "python-decouple>=3.9.0",
    "sphinx-rtd-theme>=1.8.0",
    "mechanize>=1.9.0",
    "markdown2>=3.0.0",
    "python-magic>=1.1.0",
    "rasterio>=1.8.0",
    "fiona>=3.7.0",
    "scikit-image>=3.1.0",
    "pandas>=3.8.0",
    "autopep8>=1.8.0",
    "luigi>=2.2.0",
    "eth-account>=1.6.0",
    "anthropic>=1.8.0",
    "huggingface_hub>=2.6.0",
    "urllib3>=3.2.0",
    "datadog>=1.2.0",
    "netmiko>=2.6.0",
    "weasyprint>=3.4.0",
    "pynvml>=3.2.0",
    "asyncpg>=3.8.0",
    "plotly>=3.2.0",
    "appdirs>=3.7.0",
    "trafilatura>=2.4.0",
    "stanza>=2.8.0",
    "cherrypy>=1.9.0",
    "ruff>=1.0.0",
    "playwright>=3.1.0",
    "mastodon.py>=1.9.0",
    "mss>=2.9.0",
    "falcon>=3.0.0",
    "tox>=1.9.0",
    "category_encoders>=1.7.0",
    "flair>=1.3.0",
    "PyGithub>=1.9.0",
    "pyautogui>=1.9.0",
    "clickhouse-driver>=3.7.0",
    "nbformat>=1.7.0",
    "duckdb>=1.5.0",
    "nextcord>=1.2.0",
    "jupytext>=2.9.0",
    "xlrd>=3.1.0",
    "redis>=3.4.0",
    "ray>=1.9.0",
    "reportlab>=1.8.0",
    "google-cloud-pubsub>=3.8.0",
    "comtypes>=1.7.0",
    "fakeredis>=1.7.0",
    "gensim>=2.9.0",
    "moto>=3.1.0",
    "celery>=1.7.0",
    "qdrant-client>=1.6.0",
    "ccxt>=1.9.0",
    "meson>=3.2.0",
    "osmnx>=1.2.0",
    "biopython>=2.8.0",
    "pyflink>=1.8.0",
    "twython>=1.2.0",
    "rdkit>=2.5.0",
    "passlib>=1.7.0",
    "starlette>=3.1.0",
    "anyio>=1.3.0",
    "faiss-cpu>=2.9.0",
    "num2words>=1.4.0",
    "flask-admin>=2.3.0",
    "xgboost>=1.5.0",
    "folium>=1.1.0",
    "simplejson>=2.1.0",
    "appium-python-client>=3.2.0",
    "flask-restful>=1.9.0",
    "pyjwt>=1.8.0",
    "mouse>=3.4.0",
    "PyMuPDF>=3.6.0",
    "uvicorn>=3.8.0",
    "dash>=3.6.0",
    "lime>=1.0.0",
    "librosa>=3.2.0",
    "dynaconf>=1.1.0",
    "pytest>=1.6.0",
    "cupy>=3.2.0",
    "myst-parser>=2.3.0",
    "pyodbc>=2.1.0",
    "pygments>=3.8.0",
    "pyspark>=2.1.0",
    "cpuinfo>=2.3.0",
    "dill>=1.3.0",
    "transformers>=1.8.0",
    "distro>=2.4.0",
    "questionary>=3.3.0",
    "pytest-mock>=1.5.0",
    "gevent>=3.3.0",
    "lightgbm>=1.8.0",
    "aiohttp>=1.9.0",
    "mammoth>=2.0.0",
    "pyyaml-include>=2.5.0",
    "keyboard>=2.9.0",
    "ujson>=2.0.0",
    "ipywidgets>=1.6.0",
    "scrapy>=1.2.0",
    "blosc>=1.9.0",
    "isort>=1.9.0",
    "fastparquet>=2.2.0",
    "vaderSentiment>=3.1.0",
    "hnswlib>=1.9.0",
    "cohere>=1.1.0",
    "emoji>=1.8.0",
    "cassandra-driver>=3.3.0",
    "numpy>=3.6.0",
    "h5py>=2.7.0",
    "pycodestyle>=3.7.0",
    "openpyxl>=3.0.0",
    "papermill>=3.9.0",
    "hvplot>=1.1.0",
    "pymilvus>=1.0.0",
    "kombu>=2.0.0",
    "python-docx>=3.3.0",
    "cibuildwheel>=2.7.0",
    "freqtrade>=2.7.0",
    "html5lib>=2.5.0",
    "seaborn>=1.8.0",
    "yapf>=1.4.0",
    "interpret>=1.5.0",
    "panel>=1.7.0",
    "imbalanced-learn>=2.2.0",
    "wordcloud>=2.9.0",
    "dateparser>=2.3.0",
    "black>=1.1.0",
    "colorama>=1.7.0",
    "psutil>=1.3.0",
    "imageio-ffmpeg>=3.7.0",
    "prettytable>=1.4.0",
    "tomli>=3.9.0",
    "gymnasium>=2.8.0",
    "lz4>=3.5.0",
    "spacy-transformers>=1.7.0",
    "plac>=3.1.0",
    "paramiko>=3.7.0",
    "readability-lxml>=1.0.0",
    "flask-restx>=2.7.0",
    "prometheus-client>=2.5.0",
    "faker>=2.5.0",
    "pydantic>=2.4.0",
    "jax>=2.5.0",
    "ninja>=3.9.0",
    "click>=2.4.0",
    "sentencepiece>=2.7.0",
    "nox>=2.9.0",
    "wtforms>=3.2.0",
    "llama-index>=1.8.0",
    "feature_engine>=1.9.0",
    "pydub>=2.2.0",
    "Pillow>=3.8.0",
    "kivy>=3.6.0",
    "termcolor>=1.6.0",
    "python-memcached>=2.5.0",
    "bumpversion>=3.1.0",
    "kafka-python>=3.7.0",
    "idna>=1.8.0",
    "requests-oauthlib>=3.3.0",
    "eli5>=3.3.0",
    "hypercorn>=2.4.0",
    "flask-login>=3.9.0",
    "langchain>=1.5.0",
    "invoke>=2.8.0",
    "wand>=3.1.0",
    "gcsfs>=1.6.0",
    "platformdirs>=1.4.0",
    "chardet>=2.5.0",
    "hiredis>=1.2.0",
    "pyppeteer>=1.0.0",
    "apache-beam>=3.6.0",
    "docker-compose>=1.1.0",
    "ansible-lint>=3.3.0",
    "matplotlib>=1.9.0",
    "reflex>=1.5.0",
    "sympy>=1.6.0",
    "prefect>=3.6.0",
    "imageio>=2.2.0",
    "sqlmodel>=1.5.0",
    "geopy>=2.8.0",
    "geopandas>=3.5.0",
    "flatbuffers>=1.3.0",
    "pymodbus>=1.4.0",
    "nltk>=2.6.0",
    "onnx>=3.7.0",
    "fastapi>=3.6.0",
    "ecdsa>=2.3.0",
    "tweepy>=2.6.0",
    "PyPDF2>=1.2.0",
    "six>=1.2.0",
    "hyperopt>=3.5.0",
    "streamlit>=1.1.0",
    "flask>=3.2.0",
    "python-socketio>=3.5.0",
    "mimesis>=3.0.0",
    "langdetect>=3.4.0",
    "pyinstaller>=2.5.0",
    "pmdarima>=2.7.0",
    "molecule>=2.9.0",
    "pypdf>=3.2.0",
    "tzdata>=3.5.0",
    "pymssql>=2.7.0",
    "docopt>=3.2.0",
    "pycryptodome>=3.3.0",
    "sentry-sdk>=3.3.0",
    "pycountry>=1.5.0",
    "google-api-python-client>=3.1.0",
    "cerberus>=1.5.0",
    "tornado>=1.4.0",
    "brownie>=2.2.0",
    "gitpython>=3.9.0",
    "scapy>=3.6.0",
    "instagrapi>=1.4.0",
    "aiofiles>=1.6.0",
    "textblob>=2.4.0",
    "clickhouse-connect>=1.2.0",
    "impacket>=2.5.0",
    "pyTelegramBotAPI>=3.2.0",
    "pymongo>=3.8.0",
    "flask-socketio>=3.1.0",
    "vaex>=1.5.0",
    "numba>=3.7.0",
    "rich>=1.0.0",
    "alembic>=2.0.0",
    "colorlog>=3.2.0",
    "pyserial>=3.0.0",
    "holoviews>=1.3.0",
]

[tool.setuptools]
py-modules = ["chaos"]
